testcontainers:
  host: localhost
  port: 5432
  dbName: stoker_test_db
  imageName: postgres:latest

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stoker_test_db
    driver-class-name: org.postgresql.Driver
    username: stoker_test
    password: stoker_test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
  liquibase:
    enabled: false

logging:
  level:
    jdbc:
      sqltiming: INFO
      resultsettable: DEBUG
      connection: INFO
      sqlonly: ERROR
      audit: ERROR
      resultset: ERROR